#本系统自定义配置
#服务标识每一个启用服务的容器都应该有一个不同的标识这样产生的ID就永远也不会重复 默认是AUTO 会根据机器序列按一定的机制动态生成
#config.server-id: 01
config:
  server-id: auto
  #当使用本地文件存储时的文件上传路径配置 默认/home/app/files
  basedir: /data/app/files
  #文件存储方式 normal | fast_dfs | minio | mongo_db
  storage-type: normal
  #开关访问日志记录 true开启，false关闭  默认开启
  request-log: true

#server配置
server:
  port: 9999
  servlet:
    context-path:

spring:
  #数据库配置
  #Mysql root Ro0t!@#
  datasource:
    dynamic:
      primary: master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.64.129:3306/frame?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
          username: frame
          password: EbR2BG6KxtYKRZRS
        flowable:
          driver-class-name: com.mysql.cj.jdbc.Driver
          jdbc-url: jdbc:mysql://192.168.64.129:3306/flowable?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          url: jdbc:mysql://192.168.64.129:3306/flowable?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: flowable
          password: PnyJKZhPeRwhbYa7


minio:
  url: http://127.0.0.1:9000
  username: admin
  password: admin123
  #存储桶名称
  default-bucket-name: bucket

xxl:
  job:
    ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    admin:
      addresses: http://192.168.64.129:8080/job
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: tAgQnKpTCJQkp0Z
    ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    executor:
      appname: noah
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 19991
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/run
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30

flowable:
  database-schema: flowable
  #true 会对数据库中所有表进行更新操作。如果表不存在，则自动创建。 false 抛异常
  database-schema-update: false
  use-lock-for-database-schema-update: false

#日志配置
logging:
  level:
    root: info
    #业务日志
    org.noah.web: debug
    #工作流sql
    org.flowable.engine.impl.persistence.entity.*: debug
    org.flowable.task.service.impl.persistence.entity.*: debug
