<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <#include "../../common/public.ftlh"/>
  <#include "../../common/meta.ftlh"/>
</head>
<body style="background-color: #3c98ff;">
<div id="app">
    <h1>hello Test1</h1>
</div>
</body>
<script src="${ctx}/static/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="${ctx}/static/js/plugin.js?_v=${version!}"></script>
<script>
  $(function () {


  })
</script>
</html>