<!DOCTYPE html>
<html lang="en">
<head>
  <#include "../../common/public.ftlh"/>
  <#include "../../common/meta.ftlh"/>
  <title>Noah</title>
  <style></style>
</head>
<body>
<div class="page-wrapper">
  <h1>这里是首页</h1>
</div>
</body>
<script src="${ctx}/static/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="${ctx}/static/js/plugin.js?_v=${version!}"></script>
<script>
  $(function () {

  })
</script>
</html>